backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'data'
    label: 'Data'
    identifier_field: 'type'
    folder: 'data/records'
    create: true
    slug: '{{type}}'
    extension: 'yml'
    editor:
      preview: false
    fields:
      - label: 'Type'
        name: 'type'
        widget: 'select'
        options:
          [
            'cake',
            'balloon',
            'prize',
            'cocktail',
            'bbq',
            'ice-cream',
            'hotdog',
            'champagne',
            'pizza',
            'disco-ball',
            'weight',
            'dynamite',
            'rocket',
            'cannon',
            'horse',
            'camp',
            'bomb',
            'bow',
            'extinguisher',
            'plunger',
          ]
      - label: 'Content'
        name: 'content'
        widget: 'text'
        hint: 'Message blocks should be separated with "---"'
