backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'data'
    label: 'Data'
    identifier_field: 'type'
    folder: 'data/records'
    create: false
    slug: '{{type}}'
    extension: 'yml'
    editor:
      preview: false
    fields:
      - label: 'Type'
        name: 'type'
        widget: 'string'
      - label: 'Content'
        name: 'content'
        widget: 'text'
        hint: 'Message blocks should be separated with "---"'
